CREATE TABLE BUSINESS(
ID SERIAL NOT NULL PRIMARY KEY,
ACCOUNT VARCHAR NOT NULL UNIQUE,
PASSWORD VARCHAR NOT NULL,
BUSINESS_NAME VARCHAR NOT NULL,
PHONE VARCHAR(11) NOT NULL UNIQUE,
TELEPHONE VARCHAR(13) NOT NULL UNIQUE,
CATEGORY_ID VARCHAR NOT NULL,
OPENING_TIME TIME WITH TIME ZONE NOT NULL,
CLOSING_TIME TIME WITH TIME ZONE NOT NULL,
LAST_LOGIN_IP VARCHAR NOT NULL,
DISABLED BOOLEAN DEFAULT FALSE,
CREATED_DATE_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	LAST_MODIFIED_DATE_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
		DISABLED_DATE_TIME TIMESTAMP WITH TIME ZONE
);